name: Deploy to EC2

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check user
        run: |
          whoami
          id
      - name: Deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo su
            cd /var/www/hm-laravel
            git pull
            composer install --no-dev
            php artisan migrate
            systemctl restart apache2
      - name: Alive Test
        run: date
